name: CTM - Build and push docker image
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: christmas-tree-manager
  IMAGE_REPO: florianscholzsrssoftware/christmas-tree-manager

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
          include-prerelease: false
          
      - name: Publish dotnet container
        run: dotnet publish --os linux --arch x64 /t:PublishContainer
        working-directory: ./src
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag docker image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_REPO }}:latest

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_REPO }}:latest